### PR TITLE
Added MongoDb authentication and authorization.

### PR DESCRIPTION
**Pull request by MaxM1ner**
## Description

Added MongoDb authorization and authentication. Updated Readme, docker-compose.yml and flask backend.
## Related Issue

[JIRA-35](https://partstore.atlassian.net/browse/JIRA-35)
## Motivation and Context

Prevoius database connection method was unsecure.
## How Has This Been Tested?

Tested locally with docker compose.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

[JIRA-35]: https://partstore.atlassian.net/browse/JIRA-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by olkabolkagoryashenko — APPROVED** [review]
LGFM

**Comment by muhaluk322** [comment]
Docker compose does not run successfully. Run script is missing.

**Comment by MaxM1ner** [comment]
Resolved the issue. Pull request reopened.

**Review by muhaluk322 — APPROVED** [review]
Tested locally via docker compose. Works fine.

**Pull request merged**
